### ISSUE TITLE
US 03.01.01 Make users uniquely identifiable

### ISSUE THREAD

**Issue by sfedykua** [CMPUT301F21T04/Habitize#18]
As a doer, I want to be uniquely identifiable in the system.

- Make all new users register with a unique email and unique userName 
- Let the login with their email and password 
- Compare the userNames in the database and do not allow new user

**Comment by khalida1wwin** [comment]
Worked on SignUp XML

**Comment by ShanemelAsuncion** [comment]
I worked on the Login Screen (XML, Activity and the test). It should be okay now.

**Comment by sfedykua** [comment]
Added a check for unique username before registering the user.

**Comment by khalida1wwin** [comment]
Worked on the SignUp Class.
