### ISSUE TITLE
US 06.01.01 Add location to habit event

### ISSUE THREAD

**Issue by sfedykua** [CMPUT301F21T04/Habitize#22]
As a doer, I want to a habit event to have an optional location to record where it happened.

Implementation: A habit can have multiple records. Each record can contain an image, location and comments. This dialog pop up, will show the fields to enter the record. For the optional record of location, the MapsActivity handles it and eventually passing the selected location.

**Comment by ShanemelAsuncion** [comment]
I created the MapsActivity class where in the app will ask for the user for permission to access the user's location.  Once the permission is granted, then the current location of the user will be the default location to be sent in the records. If the user wants to change the location, then the user can search through a search bar to find the location they want and set it as the location of the habit. This functionality is done. However, I there's one more thing left to do:
- connect it to firebase -> Habit

**Comment by ShanemelAsuncion** [comment]
there is a bug with the location regarding to a usage of deprecated API that is need to be fixed.

**Comment by ShanemelAsuncion** [comment]
I fixed the problem with the google api. the maps is now functional. However, I need to remove the default marker. I'm scared to push to dev so it's just sitting on my branch currently.

**Comment by ShanemelAsuncion** [comment]
Maps activity is now fully functional and done. Stan just need to link it with the record in database!!!
