### ISSUE TITLE
US 06.01.02 View habit location using map 

### ISSUE THREAD

**Issue by khalida1wwin** [CMPUT301F21T04/Habitize#40]
As a doer, I want the location for a habit event to be specified using a map within the app, with the current phone position as the default location.

Implementation: In the mapsActivity class, using the createLocationRequest method, the user is being prompted to grant permission to access the phone's location. Once that is granted, the last known location of the user is being parsed and converted into a readable address line.

**Comment by ShanemelAsuncion** [comment]
I am currently doing the geolocation functionality. The maps are already showing the current location but I have to add another functionality that enables the user to pick another location to be recorded.

**Comment by ShanemelAsuncion** [comment]
I created the MapsActivity class where in the app will ask for the user for permission to access the user's location. Once the permission is granted, then the current location of the user will be the default location to be sent in the records. If the user wants to change the location, then the user can search through a search bar to find the location they want and set it as the location of the habit. This functionality is done. However, I there's one more thing left to do:

connect it to firebase -> Habit

**Comment by ShanemelAsuncion** [comment]
This is done! It was implemented and fully functional
