### ISSUE TITLE
Functionality Goals For Project 3

### ISSUE THREAD

**Issue by rachelraso** [CMPUT301F21T04/Habitize#50]
Followers seeing other followers habits should be aimed to be in

**Comment by rpawliuk** [comment]
To get the UML diagram finished

**Comment by rpawliuk** [comment]
To finish the general progress bar and the habit progress bars

**Comment by rachelraso** [comment]
Streaks would be nice too for progress bar^

**Comment by rpawliuk** [comment]
> Streaks would be nice too for progress bar^

I agree, I would like to implement that

**Comment by ShanemelAsuncion** [comment]
Maybe editing screen too?
