### ISSUE TITLE
What is everyone working on this week?

### ISSUE THREAD

**Issue by rachelraso** [CMPUT301F21T04/Habitize#52]

**Comment by rpawliuk** [comment]
Im going to work on finishing the progress bars

**Comment by ShanemelAsuncion** [comment]
I'm trying to finish the maps and try to add the functionality that enables the user to search another location and save it in a record.

**Comment by rachelraso** [comment]
1. Tests for addHabitActivity
2. UML 
3. Today's habit + make a day habit list firebase

**Comment by sfedykua** [comment]
1. DatabaseManager class
2. Recording functionality
3. Any screens to go along with the following

**Comment by kamillahhasham** [comment]
1. Follow requests button to create new activity
2. populate images for habit
3. investigate how to implement search bar
