### ISSUE TITLE
Division of work for UML

### ISSUE THREAD

**Issue by ShanemelAsuncion** [CMPUT301F21T04/Habitize#54]
Working on creating the UML diagram.
Commented who would create each class then we connected the classes using drawio to create the UML diagram

**Comment by rpawliuk** [comment]
Login_Activity.java
Signup.java
MainActivity.java
CustomAdapter.java
AllHabitsActivity.java
AddHabitActivity.java
MyNavigationService.java
AddHabitImage.java
ViewHabitActivity.java
CustomListOfExistingFollowers.java
FollowingActivity.java

**Comment by rpawliuk** [comment]
Listing the classes to create. After this is finished we will add the connections

**Comment by rachelraso** [comment]
AddHabitBaseFragment
AddHabitImageFragment
AddHabitLocationFragment
AddHabitTabsBase
addAdapter
AllHabitsActivity
CustomAdapter
habitViewListener

**Comment by rpawliuk** [comment]
RecordAdapter.java
SignUp.java
User.java
ViewHabitActivity.java
ViewHabitBaseFragment.java
ViewHabitImageFragment.java
ViewHabitTabsBase.java
ViewRecordsFragment.java

**Comment by rachelraso** [comment]
Working On: 
AddHabitActivity.java
 AddHabitBaseFragment.java
 AddHabitImage.java
 AddHabitImageFragment.java
 AddHabitLocation.java
 AddHabitLocationFragment.java
 AddHabitTabsBase.java
 AllHabitsActivity.java
 CustomAdapter.java

**Comment by rpawliuk** [comment]
Working on AddHabitActivity.java

**Comment by rachelraso** [comment]
Working on MainActivity.java

**Comment by ShanemelAsuncion** [comment]
ViewHabitActivity.java
 ViewHabitBaseFragment.java
 ViewHabitImageFragment.java
 ViewHabitTabsBase.java
 ViewRecordsFragment.java
Login_Activity.java
SignUp.java

**Comment by rpawliuk** [comment]
Done AddHabitBaseFragment.java

**Comment by rpawliuk** [comment]
Working on  AddHabitImage.java

**Comment by rpawliuk** [comment]
Working on AddHabitImageFragment.java

**Comment by rpawliuk** [comment]
Working on AddHabitLocation.java

**Comment by ShanemelAsuncion** [comment]
> ViewHabitActivity.java ViewHabitBaseFragment.java ViewHabitImageFragment.java ViewHabitTabsBase.java ViewRecordsFragment.java Login_Activity.java SignUp.java

I finished these.

**Comment by rpawliuk** [comment]
Working on AddHabitLocationFragment.java

**Comment by rpawliuk** [comment]
Working on AddHabitTabsBase.java

**Comment by rpawliuk** [comment]
Working on AllHabitsActivity.java

**Comment by rpawliuk** [comment]
Done CustomAdapter

**Comment by rpawliuk** [comment]
Done CustomListOfExistingFollowers

**Comment by rpawliuk** [comment]
Done FollowingActivity

**Comment by rpawliuk** [comment]
Done RecordAdapter

**Comment by rpawliuk** [comment]
Done Record

**Comment by rpawliuk** [comment]
Done MyNavigationService (Can someone check this? I think that it is done but I am not sure for the fields)

**Comment by rpawliuk** [comment]
> Working on MainActivity.java

Done MainActivity.java

**Comment by ShanemelAsuncion** [comment]
> Done MyNavigationService (Can someone check this? I think that it is done but I am not sure for the fields)

Uhm okay I created this one but I refactor my code and ended up not using it so you can just delete that one. And yeah I haven't pushed my code to dev so it's not there. I can add it later tho so nw.

**Comment by kamillahhasham** [comment]
Will add the "following" related code to UML

**Comment by rpawliuk** [comment]
Rachel R and I are working on the connections with the structural, behavioural and UI class diagrams

**Comment by rpawliuk** [comment]
@rachelraso would you like to meet up in the morning for finalization

**Comment by rachelraso** [comment]
Yes! I finished the division of classes (Behavioural, Structural and UI/Activity) and am working on arrows now.

**Comment by rachelraso** [comment]
Finished the connectors/relationships for UML. Just need to be updated tomorrow with everyone's changes/new classes and functions.
