### ISSUE TITLE
Create search results Screen.

### ISSUE THREAD

**Issue by sfedykua** [CMPUT301F21T04/Habitize#61]
## Commit Hash 32198a0321495d223dee26f8ac2fc42b68217f33

On confirmation of search. The following screen should take you to a screen which holds the results of your search.[](url
![Search screen](https://user-images.githubusercontent.com/23731892/140235294-8c9301c1-c3ca-4b71-b460-3acbffcd0d06.png)
![Following Screen -2 Display search bar results – 1](https://user-images.githubusercontent.com/23731892/140235296-96ada9d0-ca7a-47f5-a06c-8e9731ab3caf.png)
)

**Comment by sfedykua** [comment]
Note: Images are ordered backwards

**Comment by kamillahhasham** [comment]
Created the UI for search results screen. 
I also implemented a search bar UI which launches a new activity to display the custom search results screen UI.
I populated the UI with mock data pending hookup to the firestore.

**Comment by kamillahhasham** [comment]
Because of merge conflicts this branch was still needs to be integrated into Dev so I've added the commit hash number to the issue for the relevant branch and changes.

**Comment by kamillahhasham** [comment]
Implemented search UI and functionality and merged code into development.
