### ISSUE TITLE
Create fragment for recording habit

### ISSUE THREAD

**Issue by sfedykua** [CMPUT301F21T04/Habitize#64]
on "checkmark" click, we should have a fragment popup which will let us set a description, image, location for the habit. priority on core functionality. Image and locations is last

**Comment by sfedykua** [comment]
Shane is set on creating the reactive UI. 
I am working on recording the result in the database

**Comment by ShanemelAsuncion** [comment]
I created the create record screen and connecting it with the image picker along with the comments and the location picker.

**Comment by sfedykua** [comment]
Recording the result has been delayed. Firestore cannot store Lists inside lists, so we cannot have a list of records inside a list of habits. New design must be found

**Comment by ShanemelAsuncion** [comment]
As a result, we are unable to connect a record (image,location and comments) to a habit. Also there is a bug with the location regarding to a usage of deprecated API that is need to be fixed.
